exports.up = function(knex) {
    return knex.raw(`
        CREATE TYPE user_role AS ENUM ('player', 'master');

        CREATE TABLE IF NOT EXISTS users
        (
            id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            username varchar(255) NOT NULL,
            password_hash varchar(500)  NOT NULL,
            role user_role DEFAULT 'player',
            created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
            CONSTRAINT users_pkey PRIMARY KEY (id),
            CONSTRAINT users_username_key UNIQUE (username)
        )
    `);
  };
  
  exports.down = function(knex) {
    return knex.raw(`
      DROP TABLE IF EXISTS users;
    `);
  };