exports.up = function(knex) {
    return knex.raw(`
        CREATE TABLE IF NOT EXISTS content_visibility
        (
            id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            content_id varchar(255) NOT NULL,
            content_type varchar(100) NOT NULL,
            hidden_for_users integer[] DEFAULT '{}'::integer[],
            created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
            updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
            CONSTRAINT content_visibility_pkey PRIMARY KEY (id)
        );
    `);
  };
  
  exports.down = function(knex) {
    return knex.raw(`
      DROP TABLE IF EXISTS content_visibility;
    `);
  };