exports.up = function(knex) {
    return knex.raw(`
        CREATE TYPE world_entry_type AS ENUM ('character', 'location', 'event', 'organization', 'item', 'other');

        CREATE TABLE IF NOT EXISTS world_entries
        (
            id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            name varchar(255) NOT NULL,
            type world_entry_type NOT NULL,
            description text,
            image_data bytea, 
            image_mime_type varchar(100), 
            created_at timestamptz DEFAULT now(),
            updated_at timestamptz DEFAULT now(),
            CONSTRAINT world_entries_pkey PRIMARY KEY (id)
        );

        CREATE INDEX idx_world_entries_type ON world_entries(type);
        CREATE INDEX idx_world_entries_name ON world_entries(name);
    `);
};

exports.down = function(knex) {
    return knex.raw(`
        DROP TABLE IF EXISTS world_entries;
        DROP TYPE IF EXISTS world_entry_type;
    `);
};