exports.up = function(knex) {
    return knex.raw(`
        CREATE TABLE IF NOT EXISTS roles
        (
            id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            name varchar(255) NOT NULL,
            description text,
            features jsonb DEFAULT '[{"id": "default", "name": "Пример", "order": 0, "description": "Описание"}]'::jsonb,
            image_path varchar(255),
            image_position varchar(50),
            CONSTRAINT roles_pkey PRIMARY KEY (id)
        )
    `);
  };
  
  exports.down = function(knex) {
    return knex.raw(`
      DROP TABLE IF EXISTS roles;
    `);
  };