exports.up = function(knex) {
    return knex.raw(`
        CREATE TABLE IF NOT EXISTS spells
        (
            id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            name varchar(255) NOT NULL DEFAULT 'Название',
            school varchar(100) NOT NULL DEFAULT 'Школа',
            level varchar(50) NOT NULL DEFAULT 'Природные силы',
            casting_time varchar(100) NOT NULL DEFAULT 'Время накладывания',
            distance varchar(100) NOT NULL DEFAULT 'Дистанция',
            duration varchar(100) NOT NULL DEFAULT 'Длительность',
            verbal boolean DEFAULT false,
            somatic boolean DEFAULT false,
            material boolean DEFAULT false,
            material_description text DEFAULT 'Материальные компоненты'::text,
            description text NOT NULL DEFAULT 'Описание'::text,
            class_id integer NOT NULL,
            created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
            updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
            CONSTRAINT spells_pkey PRIMARY KEY (id),
            CONSTRAINT spells_class_id_fkey FOREIGN KEY (class_id)
                REFERENCES classes (id) MATCH SIMPLE
                ON UPDATE NO ACTION
                ON DELETE CASCADE
        )
    `);
  };
  
  exports.down = function(knex) {
    return knex.raw(`
      DROP TABLE IF EXISTS spells;
    `);
  };