exports.up = function(knex) {
    return knex.raw(`
        CREATE TABLE IF NOT EXISTS islands
        (
            id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            name varchar(100) NOT NULL,
            x integer NOT NULL,
            y integer NOT NULL,
            monster_chance numeric(5,2) DEFAULT 0,
            pirate_chance numeric(5,2) DEFAULT 0,
            patrol_chance numeric(5,2) DEFAULT 0,
            storm_chance numeric(5,2) DEFAULT 0,
            has_harbor boolean DEFAULT false,
            created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
            updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
            CONSTRAINT islands_pkey PRIMARY KEY (id)
        );
    `);
  };
  
  exports.down = function(knex) {
    return knex.raw(`
      DROP TABLE IF EXISTS islands;
    `);
  };