exports.up = function(knex) {
    return knex.raw(`
        CREATE TABLE IF NOT EXISTS races
        (
            id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            name varchar(255) NOT NULL DEFAULT 'Новая раса',
            base_stats jsonb DEFAULT '{"bio": {"age": "", "height": "", "weight": ""}, "stats": ""}'::jsonb,
            proficiencies jsonb DEFAULT '{"weapon": "Владение"}'::jsonb,
            features jsonb DEFAULT '[{"id": "default", "name": "Пример", "order": 0, "description": "Описание"}]'::jsonb,
            underwater_breathing boolean DEFAULT false,
            water_resistance boolean DEFAULT false,
            speed integer DEFAULT 30,
            water_speed integer DEFAULT 0,
            description text DEFAULT ''::text,
            image_path varchar(255) DEFAULT '/image/Races/',
            image_position varchar(50) DEFAULT '50% 50%',
            CONSTRAINT races_pkey PRIMARY KEY (id)
        )
    `);
  };
  
  exports.down = function(knex) {
    return knex.raw(`
      DROP TABLE IF EXISTS races;
    `);
  };