exports.up = function(knex) {
    return knex.raw(`
        CREATE TABLE IF NOT EXISTS characters
        (
            id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            user_id integer,
            name varchar(255) NOT NULL,
            class_name text,
            race_name text,
            role_id integer,
            devil_fruit_id integer,
            will_id integer,
            description text,
            stats jsonb DEFAULT '{"wisdom": 10, "charisma": 10, "strength": 10, "dexterity": 10, "constitution": 10, "intelligence": 10}'::jsonb,
            proficiencies jsonb,
            saving_throws jsonb DEFAULT '[]'::jsonb,
            skills jsonb DEFAULT '[]'::jsonb,
            equipment jsonb DEFAULT '[]'::jsonb,
            abilities jsonb DEFAULT '[]'::jsonb,
            spells jsonb DEFAULT '[]'::jsonb,
            created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
            level integer DEFAULT 1,
            background text,
            alignment text,
            current_hp integer,
            max_hp integer,
            temp_hp integer DEFAULT 0,
            hit_dice text,
            inspiration boolean DEFAULT false,
            traits jsonb DEFAULT '{"bonds": "", "flaws": "", "ideals": "", "personality": ""}'::jsonb,
            attacks jsonb DEFAULT '[]'::jsonb,
            features jsonb DEFAULT '[]'::jsonb,
            CONSTRAINT characters_pkey PRIMARY KEY (id),
            CONSTRAINT characters_user_id_fkey FOREIGN KEY (user_id)
                REFERENCES users (id) MATCH SIMPLE
                ON UPDATE NO ACTION
                ON DELETE CASCADE
        );

    `);
  };
  
  exports.down = function(knex) {
    return knex.raw(`
      DROP TABLE IF EXISTS characters;
    `);
  };