exports.up = function(knex) {
    return knex.raw(`
        CREATE TYPE devil_type AS ENUM ('Paramecia', 'Zoan', 'Logia');

        CREATE TABLE IF NOT EXISTS devil_fruits
        (
            id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            name varchar(255) NOT NULL,
            type devil_type NULL,
            description text NULL,
            abilities jsonb DEFAULT '{"rarity": "Uncommon", "features": [], "awakening": null}'::jsonb,
            appearance text,
            creature jsonb DEFAULT '{"ac": 10, "hp": "1d10", "name": "", "type": "beast", "speed": "30 ft", "stats": {"wisdom": 10, "charisma": 10, "strength": 10, "dexterity": 10, "constitution": 10, "intelligence": 10}, "skills": "", "abilities": []}'::jsonb,
            water_vulnerability boolean DEFAULT true,
            CONSTRAINT devil_fruits_pkey PRIMARY KEY (id)
        );
    `);
  };
  
  exports.down = function(knex) {
    return knex.raw(`
      DROP TABLE IF EXISTS devil_fruits;
    `);
  };