exports.up = function(knex) {
    return knex.raw(`
        CREATE TABLE IF NOT EXISTS subclasses
        (
            id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            class_id integer,
            name varchar(255) NOT NULL,
            description text,
            features jsonb DEFAULT '{"levels": [{"level": 1, "features": ""}], "columns": [{"key": "level", "title": "Уровень"}, {"key": "skills", "title": "Особенности"}]}'::jsonb,
            CONSTRAINT subclasses_pkey PRIMARY KEY (id),
            CONSTRAINT subclasses_class_id_fkey FOREIGN KEY (class_id)
                REFERENCES classes (id) MATCH SIMPLE
                ON UPDATE NO ACTION
                ON DELETE NO ACTION
        );
    `);
  };
  
  exports.down = function(knex) {
    return knex.raw(`
      DROP TABLE IF EXISTS subclasses;
    `);
  };