exports.up = function(knex) {
    return knex.raw(`

        CREATE TABLE IF NOT EXISTS classes
        (
            id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            name varchar(255) NOT NULL,
            description text,
            proficiencies jsonb DEFAULT '{"armor": "", "tools": "", "skills": "", "weapons": [], "equipment": [], "savingThrows": []}'::jsonb,
            features jsonb DEFAULT '{"levels": [{"bm": 2, "level": 1, "skills": []}], "columns": [{"key": "level", "title": "Уровень"}, {"key": "bm", "title": "БМ"}, {"key": "skills", "title": "Навыки"}]}'::jsonb,
            image_position varchar(50) DEFAULT 'center',
            image_path text DEFAULT '\image\'::text,
            base_stats varchar(100),
            hit_dice integer NOT NULL DEFAULT 8,
            CONSTRAINT classes_pkey PRIMARY KEY (id)
        );
    `);
  };
  
  exports.down = function(knex) {
    return knex.raw(`
      DROP TABLE IF EXISTS classes;
    `);
  };